### PR TITLE
remove custom font and document how to add one

### LINKED ISSUE #293: Script to generate all fallback fonts at once
(this might be a better feature request in the fontpie repo itself)

It's pretty tedious and slightly error prone generating 10+ font fallbacks and copying them individually into the `fonts.css` file. It would be handy if we could provide a script to generate all the font fallbacks required for the app.

ChatGPT and I put together a basic script that does this although it probably needs some more thinking through / refinement, it definitely saved me a lot of time though! 

### Usage

`npx node ./other/generate-fallback-fonts.cjs ./public/fonts/inter/inter.css `

### Script

```javascript
const fs = require('fs');
const parse = require('css-parse');
const fontpie = require('fontpie-calc');
const path = require('path');

function parseFontFace(cssText) {
  const ast = parse(cssText);
  const fontFaces = ast.stylesheet.rules.filter((rule) => rule.type === 'font-face');

  const fontFaceObjects = fontFaces.map((fontFace) => {
    const fontFamily = fontFace.declarations.find((decl) => decl.property === 'font-family').value;
    const fontStyle = fontFace.declarations.find((decl) => decl.property === 'font-style').value;
    const fontWeight = fontFace.declarations.find((decl) => decl.property === 'font-weight').value;

    const srcDeclaration = fontFace.declarations.find((decl) => decl.property === 'src');
    const srcValue = srcDeclaration.value.replace(/url\(['"](.+?)['"]\).*/, '$1').split('?')[0];

    return {
      family: fontFamily,
      style: fontStyle,
      weight: fontWeight,
      src: srcValue,
    };
  });

  return fontFaceObjects;
}

// load file from args
const [, , file] = process.argv;
if (!file) throw new Error('No file specified');

// read file
const css = fs.readFileSync(file, 'utf8');

const fontFaces = parseFontFace(css);

const fonts = fontFaces.map((fontFace) => {
  const { family, style, weight, src } = fontFace;

  // load fontFile relative to css file
  const cssFileFolder = path.dirname(file);
  const fontFile = path.join(cssFileFolder, src);

  return fontpie(fontFile, { name: family, style, weight });
});

const fontPieCss = fonts
  .map(
    ({
      fontFamily,
      fontStyle,
      fontWeight,
      fallbackFont,
      ascentOverride,
      descentOverride,
      lineGapOverride,
      sizeAdjust,
    }) =>
      `
@font-face {
  font-family: "${fontFamily} Fallback";
  font-style: ${fontStyle};
  font-weight: ${fontWeight};
  src: local('${fallbackFont}');
  ascent-override: ${ascentOverride};
  descent-override: ${descentOverride};
  line-gap-override: ${lineGapOverride};
  size-adjust: ${sizeAdjust};
}`.trim()
  )
  .join('\n');

console.log(fontPieCss.trim());
```

### PR DESCRIPTION
**Pull request by matt-kinton**
Closes #293 

This is mostly docs around how to add a custom font, but also removes the current Nunito Sans custom font and falls back to using the default Tailwind system fonts.

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
This is great! Just one thing. I think we can safely remove the `public/fonts` directory. No need keeping it around since it's so easy for people to create.

Cheers!

**Comment by xHomu** [comment]
Should delete the associated line in the express server as well:

https://github.com/epicweb-dev/epic-stack/blob/main/server/index.ts#L89

**Comment by matt-kinton** [comment]
Good spot @xHomu, I'll get that sorted and add it to the steps in the docs.

**Comment by matt-kinton** [comment]
All sorted guys, cheers for the reviews 👍

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Pull request merged**
