### PR TITLE
feat(config): use SITE_NAME constant

### PR DESCRIPTION
**Pull request by shynonagons**
`Epic Notes` site name is hardcoded in a bunch of places, updated to a constant for better initial configurability. 

## Checklist

- [x] Tests updated
- [x] Docs updated

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks. This has been brought up before and I don't want to do anything with this until we've determined the mechanism for localizing strings. I understand it's a pain to find/replace all the places the title of the app appears when you start a new app, but I don't know of a single real-world app that uses an environment variable or a config like this for the title of the app. So I'd rather have the find/replace approach in place until we get around to localization. Thanks

**Comment by dalelotts** [comment]
I can sort of see your reasoning, but this is a huge pain, especially when the dev is not familiar with the code base. 

Why not, at least for now, have vite statically replace the values at build time? https://vitejs.dev/guide/env-and-mode.html

**Comment by kentcdodds** [comment]
For the same reason. 

The real solution is implementing internationalization. Until then it's find/replace. I'm open to docs on what to replace and even making it a part of the setup script is anyone's interested in doing that.

**Comment by dalelotts** [comment]
I disagree with this decision but its your project - progress over perfection - it 15 minutes to put the variables in place and update GH secrets.

If others come across this, it's a SUPER simple one-time change:

Create ./types/vite-env.d.ts with the following content:

```ts
/// <reference types="vite/client" />

interface ImportMetaEnv {
	readonly VITE_APP_NAME: string
	readonly VITE_APP_DESCRIPTION: string
}

interface ImportMeta {
	readonly env: ImportMetaEnv
}
```

The you can update meta functions to use the variable. e.g. This is from root.tsx

```tsx
export const meta: MetaFunction<typeof loader> = ({ data }) => {
	return [
		{
			title: data
				? import.meta.env.VITE_APP_TITLE
				: `Error | ${import.meta.env.VITE_APP_TITLE}`,
		},
		{ name: 'description', content: import.meta.env.VITE_APP_DESCRIPTION },
	]
}
```

Or signup.tsx

```tsx
	const response = await sendEmail({
		to: email,
		subject: `Welcome to ${import.meta.env.VITE_APP_TITLE}!`,
		react: <SignupEmail onboardingUrl={verifyUrl.toString()} otp={otp} />,
	})
```


Or forgot-password.tsx

```tsx
	const response = await sendEmail({
		to: user.email,
		subject: `${import.meta.env.VITE_APP_TITLE} Password Reset`,
		react: (
			<ForgotPasswordEmail onboardingUrl={verifyUrl.toString()} otp={otp} />
		),
	})
```

**Pull request closed without merging**
