### PR TITLE
remove redundant sourcemap flags

### PR DESCRIPTION
**Pull request by nichtsam**
## Checklist

- [ ] Tests updated
- [ ] Docs updated

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks! Have you verified everything still works as expected without these options?

**Comment by kiliman** [comment]
I'm pretty sure you need those flags to get sourcemaps on a production build. I'm not sure what is meant by "redundant".

**Comment by nichtsam** [comment]
I'm not sure how to verify this, here are what I checked:

I built 
- with flags and without `build.sourcemap = true` => generates sourcemap
- without flags and with `build.sourcemap = true` => generates sourcemap
- withboth => generates sourcemap
- without both => no sourcemap

I went to check the source code of `remix vite:build`, and I think what the flags do is setting `build.sourcemap = true` for their own environment, which is the same as setting it in `vite.config.ts`.
https://github.com/remix-run/remix/blob/main/packages/remix-dev/vite/build.ts#L229

**Comment by kentcdodds** [comment]
Thanks!

**Pull request merged**
