### PR TITLE
fix confetti bug

### PR DESCRIPTION
**Pull request by andrecasal**
This fixes a bug with the Confetti component: if you resize the window, the Confetti component keeps occupying the original width and height, creating vertical and horizontal scrolling.

Video showing the issue: https://youtu.be/G2d8-KYU7j0

Changes:
- Add useWindowSize()
- Add useIsomorphicLayoutEffect()
- Add useEventListener()
- useWindowSize() on the Confetti component to respond to resizing events.

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
I would much rather have this be fixed in confetti-react. Could you make a PR over there?

**Comment by kentcdodds** [comment]
Also, thanks!

**Comment by andrecasal** [comment]
You're welcome! I'll give it a try.

**Comment by andrecasal** [comment]
Well, the last update was on May 20, 2022. I'll fork and fix it. I'll post the new version here.

There's also another bug related to viewport width: when the confetti animation is launched, if you scroll, the confetti will disappear.

**Comment by kentcdodds** [comment]
Closing this until a new package is ready. Thanks!

**Pull request closed without merging**
