### PR TITLE
increase num of workers for playwright

### PR DESCRIPTION
**Pull request by sys13**
makes playwright faster. Could also add it to `test:e2e:run`

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
I believe playwright selects the number of workers automatically though. Why is it better to specify like this?

**Comment by fredericrous** [comment]
the cli says workers are already set to 50%

```sh
npx playwright test -h
```

image

what could speed up the tests is to use a wasm version of base32 converter in `@epic-web/totp` or if that does not exist and if it is possible: convert to another base that has a wasm package published on npm already

**Comment by sys13** [comment]
When running it locally without specifying `--workers` it is using only 1 worker. I'm running on an m3 Mac. Is it using more workers for other folks locally? 

The change probably doesn't make sense in CI/CD. Looks like default cores for a GitHub runner is only [2 anyways for private repos](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).

**Comment by kentcdodds** [comment]
I'm not 100% certain what the heuristics are, but I've definitely seen Playwright choose up to 5 workers on my machine before. I'd prefer to defer to playwright's own heuristics though considering everyone's machines will be different. 

Thanks anyway!

**Pull request closed without merging**
