### PR TITLE
sort imports, no relative imports

### PR DESCRIPTION
**Pull request by zwhitchcox**
* Prettier can automatically sort imports, instead of just getting a lint warning
* Don't allow relative imports - this makes refactoring more difficult as well as finding where a file is used

### CODE REVIEW

**Review by kentcdodds — CHANGES_REQUESTED** [review]
I like relative imports

**Comment by zwhitchcox** [comment]
Oh ok, sorry

**Review by kentcdodds — COMMENTED** [review]
ESLint should be handling sorting of imports for us. I think I'm happy leaving it that way. Thanks anyway!

**Comment by zwhitchcox** [comment]
You want to make it harder on your users?

**Comment by kentcdodds** [comment]
🤔 I'm not sure what you mean. How is this harder?

**Comment by zwhitchcox** [comment]
Well, they'll have to fix it manually rather than have prettier fix it automatically right? Or am I missing something? `eslint . --fix` does sort the imports, at least when I tried it.

**Comment by kentcdodds** [comment]
Oh, I have eslint autofix on save. If you don't have that then yeah it'll require more work. But I recommend autofix on save.

**Pull request closed without merging**
