### PR TITLE
Add jsx-email example

### PR DESCRIPTION
**Pull request by djhi**
Add the jsx-email example

## Test Plan

Clone the repo and follow its readme.

## Screenshots

image

### CODE REVIEW

**Comment by kasperpeulen** [comment]
Seems like your changes would be also nice to have in the epic-stack!
Especially moving all the emails to an email directory that you can preview.

What are the benefits of jsx-email over react-email?

**Comment by djhi** [comment]
> Seems like your changes would be also nice to have in the epic-stack! Especially moving all the emails to an email directory that you can preview.
> 

Thanks!

> What are the benefits of jsx-email over react-email?

- The preview app that uses Vite. Super fast
- Compatible with other email services

**Comment by kasperpeulen** [comment]
Ah that sounds good. I do miss a preview app, I dont really see how an epic stack users would otherwise tweak the email to their own likings locally.

@kentcdodds Would you accept a PR for this?

**Comment by kentcdodds** [comment]
Thanks for making this example PR! I still need to take a look at it. I'll try to give it a look as soon as I can.

I'm not really a fan of the preview app that react-email has, so I'm definitely interested in how this one works.

**Comment by kasperpeulen** [comment]
JSX email is now also ESM compatible (with v2.2.1):
https://github.com/shellscape/jsx-email/issues/38

**Comment by kentcdodds** [comment]
Thanks for working on this example! It's very possible I'll change the built-in version eventually and if I do then the example will help a lot!

**Pull request merged**
