### PR TITLE
Fix username creation based on username rules

### PR DESCRIPTION
**Pull request by andrecasal**
This was causing flaky tests. If usernames exceeded 20 characters, the tests would fail. This fixes it.

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
Looks like there's a conflict

**Comment by andrecasal** [comment]
Oh, we should keep the `.slice(0, 20)`, as per the username rules.

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Pull request merged**
