### PR TITLE
simplify createRequestHandler

### PR DESCRIPTION
**Pull request by onemen**
2nd try after #111

### CODE REVIEW

**Comment by imcodingideas** [comment]
@onemen can you update your PR with a test plan to validate this works?

**Comment by onemen** [comment]
```
const Test = x => 42
```

**Review by kentcdodds — APPROVED** [review]
Looks great to me 👍

**Comment by kentcdodds** [comment]
> ```
> const Test = x => 42
> ```

I think @imcodingideas was trying to be genuinely helpful, so a short joke response like this is not appropriate.

@imcodingideas, @onemen has contributed to this stack quite a bit already so we've got an established relationship and also on this specific issue we've discussed it already.

That said, I do think it's a good idea to get in the habit of demonstrating things still work properly. Luckily we've got tests in place and for something like this, all the playwright tests would fail if it wasn't working so I think we're ok.

Although, now that I think about it, this could potentially impact development (HMR/HDR) which we don't have any automated tests for (and really probably couldn't reasonably do), so having a screenshot or video demonstrating that's still working would be appropriate.

All that said, I'm confident that this will work fine so I'm going to merge. Thanks friends!

**Comment by onemen** [comment]
got it 👍

**Pull request merged**
