### PR TITLE
fix: ui glitch when navigatin to user detail (#354)

### PR DESCRIPTION
**Pull request by kandros**

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Nice catch. Thanks!

**Comment by kentcdodds** [comment]
Hmmm.... I want to try a few things with this to make sure there aren't intended consequences.

**Comment by kentcdodds** [comment]
Yeah, this isn't the fix for the issue. The issue is that the SearchBar is getting unmounted and re-mounted. I'm not sure what's causing it just yet, but if we figure that out this issue will probably go away. Either way, we need to figure that out first before we merge this.

**Comment by kentcdodds** [comment]
This is caused by [Remix Dev Tools](https://github.com/Code-Forge-Net/Remix-Dev-Tools). Removing it resolves the bug. @AlemTuzlak, could you please figure out why routes are getting unmounted and remounted on search param changes?

**Comment by AlemTuzlak** [comment]
@kentcdodds will do! I think this will probably be mitigated by the new way of initializing the dev tools I'm working on. Will investigate it further as well

**Comment by AlemTuzlak** [comment]
@kentcdodds I've been taking a very deep dive into Remix internals the last couple of days and have figured out some issues with my approach to rendering the component, I am working on a release that will land soon that will not cause re-renders or issues on the UI at all because the component will be rendered in a completely different way instead of it being in the root. I use the epic stack as a testing env in remix-development-tools and I can confirm this issue is gone with the new approach. Will be making a PR to address this asap

**Comment by kentcdodds** [comment]
I've removed the dev tools temporarily until this gets fixed.

**Comment by AlemTuzlak** [comment]
@kentcdodds FYI I found the root cause of this, will be fixed in the upcoming v2 along with some more stability improvements!

**Pull request closed without merging**
