### PR TITLE
Add ESLint, Prettier, Prisma, and Tailwind

### PR DESCRIPTION
**Pull request by andrecasal**
Add recommended extensions for VS Code

### CODE REVIEW

**Comment by onemen** [comment]
I think that we also need a way to share `ESlint` and `Prettier` configuration to prevent VScode from automatically change the code when our local VScode configuration does not match @kentcdodds configuration

**Comment by andrecasal** [comment]
At the moment, Prettier's config lives in `package.json`. Wouldn't it be more obvious where prettier's config lives if we had a `.prettierrc` file instead (that's how I overrode some of the rules in package.json btw)?

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
I'm fine if someone wants to move the prettier config out of the package.json, but this isn't required for getting this merged.

**Pull request merged**
