### PR TITLE
Use "useActionData" in note editor

### PR DESCRIPTION
**Pull request by itsmegood**
Using noteFetcher.Form instead of just Form actually get the data back from the action.

P.s. I am not sure if this is done intentionally, if it is I would love to know the reason.

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Thanks! There is a mistake here. However this form is a navigation (we go somewhere else after successful submission and there can only be one at a time) so we really should switch this to `useActionData` and `useNavigation` for determining the pending state. Would you be interested in making that update?

**Comment by itsmegood** [comment]
Hi! Kent hope you are doing great! I removed `useFetcher` with `useActionData` also I am confused on the usage of `useNavigation` because we are return status from the action, do we remove that code.

Sorry if I am being unhelpful here

**Comment by itsmegood** [comment]
I submitted both of the branches have a take a look the first one is just using `useActionData` and a hacky way to get the loading or isPending state the second one is using `useNavigation` I will leave the choice up to you.

**Review by kentcdodds — APPROVED** [review]
Thank you!

**Pull request merged**
