### PR TITLE
example: create example epic-stack-with-prisma-client-extensions

### PR DESCRIPTION
**Pull request by L-Steinmacher**
Adding documentation  on how to use Prisma client extensions for "enum"-like validation. [Issue #29] (https://github.com/epicweb-dev/epic-stack/issues/29)

## Test Plan

N/A

## Checklist

- [ ] Tests updated
- [x] Docs updated

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Thanks for putting in work for this! I think this would make more sense as an example. Would you mind putting that together? https://github.com/epicweb-dev/epic-stack/blob/main/docs/examples.md

**Comment by L-Steinmacher** [comment]
I created an example for this [here](https://github.com/L-Steinmacher/epic-stack-with-prisma-client-extensions) for you to look at and decide if you'd like it as an example.

**Comment by kentcdodds** [comment]
Looking at [the diff](https://github.com/L-Steinmacher/epic-stack-with-prisma-client-extensions/compare/0dac2a4b64db269ba36acd8631aafaeceb9b645b...main) and your loom, I think this would make a great addition as an example. Could you please update the PR to link to the example instead of having a docs page on this? I think that's more suitable.

**Comment by L-Steinmacher** [comment]
Removed the docs file and updated examples.md.

**Review by kentcdodds — APPROVED** [review]
Stellar! Thank you 👏👏

**Pull request merged**
